# time how long it takes to run a basic bioinformatics pipeline
# call with time (perl test_timing_workflow.pl  2>test.err) 2>>total.err
# individual times to test.err, total replicate time to total.err

# print something like a UID for this run
$runID = "Run ID-".join('-',@ARGV).'-'.time()."\n";
warn $runID;
print $runID;

# How many lines from the SRA to include
$num_files_in_short_alignment = $ARGV[0];
warn "Number of input seqfile lines:[$num_files_in_short_alignment]\n";

#RAxML location
$bin_raxml = '/Applications/Phylogenetics/RAxML/RAxML-7.2.8-ALPHA/raxmlHPC-PTHREADS';
warn "Location of raxmlHPC:[$bin_raxml]\n";

#number of threads to run
$threads = $ARGV[1];
warn "Max threads to run:[$threads]\n";

# IMPORTANT!
# setup steps:
#	DELETE OLD RAXML TMPFILES
#	head the ../MG-RAST/mgm4550336.3.350.genecalling.faa file to short.input.faa
system("head -n $num_files_in_short_alignment mgm4550336.3.350.genecalling.faa > ../MG-RAST/short.input.faa");
#	copy the ../CEGMA_input_data_aa to ../concat_alignment_hits/ thus WIPING the previous hits
system("cp ../CEGMA_input_data_aa/by_gene* ../concat_alignment_hits/ ");
# 	make sure phylogenetics dir exists and is empty
system("rm -r ../phylogenetics");
system("mkdir ../phylogenetics");


@gene_list_long = (
"../concat_alignment_hits/by_gene_KOG0002",
"../concat_alignment_hits/by_gene_KOG0003",
"../concat_alignment_hits/by_gene_KOG0018",
"../concat_alignment_hits/by_gene_KOG0019",
"../concat_alignment_hits/by_gene_KOG0025",
"../concat_alignment_hits/by_gene_KOG0047",
"../concat_alignment_hits/by_gene_KOG0062",
"../concat_alignment_hits/by_gene_KOG0073",
"../concat_alignment_hits/by_gene_KOG0077",
"../concat_alignment_hits/by_gene_KOG0084",
"../concat_alignment_hits/by_gene_KOG0092",
"../concat_alignment_hits/by_gene_KOG0094",
"../concat_alignment_hits/by_gene_KOG0100",
"../concat_alignment_hits/by_gene_KOG0102",
"../concat_alignment_hits/by_gene_KOG0103",
"../concat_alignment_hits/by_gene_KOG0122",
"../concat_alignment_hits/by_gene_KOG0142",
"../concat_alignment_hits/by_gene_KOG0173",
"../concat_alignment_hits/by_gene_KOG0174",
"../concat_alignment_hits/by_gene_KOG0175",
"../concat_alignment_hits/by_gene_KOG0176",
"../concat_alignment_hits/by_gene_KOG0177",
"../concat_alignment_hits/by_gene_KOG0179",
"../concat_alignment_hits/by_gene_KOG0180",
"../concat_alignment_hits/by_gene_KOG0181",
"../concat_alignment_hits/by_gene_KOG0182",
"../concat_alignment_hits/by_gene_KOG0183",
"../concat_alignment_hits/by_gene_KOG0184",
"../concat_alignment_hits/by_gene_KOG0185",
"../concat_alignment_hits/by_gene_KOG0188",
"../concat_alignment_hits/by_gene_KOG0190",
"../concat_alignment_hits/by_gene_KOG0209",
"../concat_alignment_hits/by_gene_KOG0211",
"../concat_alignment_hits/by_gene_KOG0225",
"../concat_alignment_hits/by_gene_KOG0233",
"../concat_alignment_hits/by_gene_KOG0258",
"../concat_alignment_hits/by_gene_KOG0261",
"../concat_alignment_hits/by_gene_KOG0264",
"../concat_alignment_hits/by_gene_KOG0271",
"../concat_alignment_hits/by_gene_KOG0276",
"../concat_alignment_hits/by_gene_KOG0279",
"../concat_alignment_hits/by_gene_KOG0285",
"../concat_alignment_hits/by_gene_KOG0289",
"../concat_alignment_hits/by_gene_KOG0291",
"../concat_alignment_hits/by_gene_KOG0292",
"../concat_alignment_hits/by_gene_KOG0302",
"../concat_alignment_hits/by_gene_KOG0313",
"../concat_alignment_hits/by_gene_KOG0318",
"../concat_alignment_hits/by_gene_KOG0327",
"../concat_alignment_hits/by_gene_KOG0328",
"../concat_alignment_hits/by_gene_KOG0329",
"../concat_alignment_hits/by_gene_KOG0330",
"../concat_alignment_hits/by_gene_KOG0331",
"../concat_alignment_hits/by_gene_KOG0344",
"../concat_alignment_hits/by_gene_KOG0346",
"../concat_alignment_hits/by_gene_KOG0357",
"../concat_alignment_hits/by_gene_KOG0358",
"../concat_alignment_hits/by_gene_KOG0359",
"../concat_alignment_hits/by_gene_KOG0361",
"../concat_alignment_hits/by_gene_KOG0362",
"../concat_alignment_hits/by_gene_KOG0363",
"../concat_alignment_hits/by_gene_KOG0364",
"../concat_alignment_hits/by_gene_KOG0365",
"../concat_alignment_hits/by_gene_KOG0366",
"../concat_alignment_hits/by_gene_KOG0367",
"../concat_alignment_hits/by_gene_KOG0371",
"../concat_alignment_hits/by_gene_KOG0372",
"../concat_alignment_hits/by_gene_KOG0373",
"../concat_alignment_hits/by_gene_KOG0376",
"../concat_alignment_hits/by_gene_KOG0394",
"../concat_alignment_hits/by_gene_KOG0397",
"../concat_alignment_hits/by_gene_KOG0400",
"../concat_alignment_hits/by_gene_KOG0402",
"../concat_alignment_hits/by_gene_KOG0407",
"../concat_alignment_hits/by_gene_KOG0418",
"../concat_alignment_hits/by_gene_KOG0419",
"../concat_alignment_hits/by_gene_KOG0420",
"../concat_alignment_hits/by_gene_KOG0424",
"../concat_alignment_hits/by_gene_KOG0434",
"../concat_alignment_hits/by_gene_KOG0441",
"../concat_alignment_hits/by_gene_KOG0450",
"../concat_alignment_hits/by_gene_KOG0460",
"../concat_alignment_hits/by_gene_KOG0462",
"../concat_alignment_hits/by_gene_KOG0466",
"../concat_alignment_hits/by_gene_KOG0468",
"../concat_alignment_hits/by_gene_KOG0469",
"../concat_alignment_hits/by_gene_KOG0477",
"../concat_alignment_hits/by_gene_KOG0481",
"../concat_alignment_hits/by_gene_KOG0495",
"../concat_alignment_hits/by_gene_KOG0523",
"../concat_alignment_hits/by_gene_KOG0524",
"../concat_alignment_hits/by_gene_KOG0530",
"../concat_alignment_hits/by_gene_KOG0534",
"../concat_alignment_hits/by_gene_KOG0544",
"../concat_alignment_hits/by_gene_KOG0556",
"../concat_alignment_hits/by_gene_KOG0559",
"../concat_alignment_hits/by_gene_KOG0563",
"../concat_alignment_hits/by_gene_KOG0567",
"../concat_alignment_hits/by_gene_KOG0602",
"../concat_alignment_hits/by_gene_KOG0622",
"../concat_alignment_hits/by_gene_KOG0625",
"../concat_alignment_hits/by_gene_KOG0631",
"../concat_alignment_hits/by_gene_KOG0650",
"../concat_alignment_hits/by_gene_KOG0659",
"../concat_alignment_hits/by_gene_KOG0675",
"../concat_alignment_hits/by_gene_KOG0679",
"../concat_alignment_hits/by_gene_KOG0683",
"../concat_alignment_hits/by_gene_KOG0687",
"../concat_alignment_hits/by_gene_KOG0688",
"../concat_alignment_hits/by_gene_KOG0727",
"../concat_alignment_hits/by_gene_KOG0728",
"../concat_alignment_hits/by_gene_KOG0729",
"../concat_alignment_hits/by_gene_KOG0734",
"../concat_alignment_hits/by_gene_KOG0741",
"../concat_alignment_hits/by_gene_KOG0756",
"../concat_alignment_hits/by_gene_KOG0758",
"../concat_alignment_hits/by_gene_KOG0767",
"../concat_alignment_hits/by_gene_KOG0780",
"../concat_alignment_hits/by_gene_KOG0784",
"../concat_alignment_hits/by_gene_KOG0785",
"../concat_alignment_hits/by_gene_KOG0787",
"../concat_alignment_hits/by_gene_KOG0788",
"../concat_alignment_hits/by_gene_KOG0815",
"../concat_alignment_hits/by_gene_KOG0817",
"../concat_alignment_hits/by_gene_KOG0820",
"../concat_alignment_hits/by_gene_KOG0829",
"../concat_alignment_hits/by_gene_KOG0852",
"../concat_alignment_hits/by_gene_KOG0853",
"../concat_alignment_hits/by_gene_KOG0857",
"../concat_alignment_hits/by_gene_KOG0861",
"../concat_alignment_hits/by_gene_KOG0862",
"../concat_alignment_hits/by_gene_KOG0871",
"../concat_alignment_hits/by_gene_KOG0876",
"../concat_alignment_hits/by_gene_KOG0878",
"../concat_alignment_hits/by_gene_KOG0880",
"../concat_alignment_hits/by_gene_KOG0888",
"../concat_alignment_hits/by_gene_KOG0894",
"../concat_alignment_hits/by_gene_KOG0898",
"../concat_alignment_hits/by_gene_KOG0922",
"../concat_alignment_hits/by_gene_KOG0927",
"../concat_alignment_hits/by_gene_KOG0933",
"../concat_alignment_hits/by_gene_KOG0934",
"../concat_alignment_hits/by_gene_KOG0935",
"../concat_alignment_hits/by_gene_KOG0937",
"../concat_alignment_hits/by_gene_KOG0938",
"../concat_alignment_hits/by_gene_KOG0948",
"../concat_alignment_hits/by_gene_KOG0952",
"../concat_alignment_hits/by_gene_KOG0959",
"../concat_alignment_hits/by_gene_KOG0960",
"../concat_alignment_hits/by_gene_KOG0964",
"../concat_alignment_hits/by_gene_KOG0969",
"../concat_alignment_hits/by_gene_KOG0985",
"../concat_alignment_hits/by_gene_KOG0989",
"../concat_alignment_hits/by_gene_KOG0991",
"../concat_alignment_hits/by_gene_KOG0996",
"../concat_alignment_hits/by_gene_KOG1036",
"../concat_alignment_hits/by_gene_KOG1047",
"../concat_alignment_hits/by_gene_KOG1058",
"../concat_alignment_hits/by_gene_KOG1062",
"../concat_alignment_hits/by_gene_KOG1068",
"../concat_alignment_hits/by_gene_KOG1077",
"../concat_alignment_hits/by_gene_KOG1078",
"../concat_alignment_hits/by_gene_KOG1088",
"../concat_alignment_hits/by_gene_KOG1098",
"../concat_alignment_hits/by_gene_KOG1099",
"../concat_alignment_hits/by_gene_KOG1112",
"../concat_alignment_hits/by_gene_KOG1123",
"../concat_alignment_hits/by_gene_KOG1131",
"../concat_alignment_hits/by_gene_KOG1137",
"../concat_alignment_hits/by_gene_KOG1145",
"../concat_alignment_hits/by_gene_KOG1148",
"../concat_alignment_hits/by_gene_KOG1149",
"../concat_alignment_hits/by_gene_KOG1158",
"../concat_alignment_hits/by_gene_KOG1159",
"../concat_alignment_hits/by_gene_KOG1180",
"../concat_alignment_hits/by_gene_KOG1185",
"../concat_alignment_hits/by_gene_KOG1211",
"../concat_alignment_hits/by_gene_KOG1235",
"../concat_alignment_hits/by_gene_KOG1241",
"../concat_alignment_hits/by_gene_KOG1255",
"../concat_alignment_hits/by_gene_KOG1268",
"../concat_alignment_hits/by_gene_KOG1272",
"../concat_alignment_hits/by_gene_KOG1291",
"../concat_alignment_hits/by_gene_KOG1299",
"../concat_alignment_hits/by_gene_KOG1300",
"../concat_alignment_hits/by_gene_KOG1301",
"../concat_alignment_hits/by_gene_KOG1322",
"../concat_alignment_hits/by_gene_KOG1335",
"../concat_alignment_hits/by_gene_KOG1342",
"../concat_alignment_hits/by_gene_KOG1349",
"../concat_alignment_hits/by_gene_KOG1350",
"../concat_alignment_hits/by_gene_KOG1351",
"../concat_alignment_hits/by_gene_KOG1353",
"../concat_alignment_hits/by_gene_KOG1355",
"../concat_alignment_hits/by_gene_KOG1358",
"../concat_alignment_hits/by_gene_KOG1367",
"../concat_alignment_hits/by_gene_KOG1370",
"../concat_alignment_hits/by_gene_KOG1373",
"../concat_alignment_hits/by_gene_KOG1374",
"../concat_alignment_hits/by_gene_KOG1390",
"../concat_alignment_hits/by_gene_KOG1393",
"../concat_alignment_hits/by_gene_KOG1394",
"../concat_alignment_hits/by_gene_KOG1415",
"../concat_alignment_hits/by_gene_KOG1430",
"../concat_alignment_hits/by_gene_KOG1433",
"../concat_alignment_hits/by_gene_KOG1439",
"../concat_alignment_hits/by_gene_KOG1448",
"../concat_alignment_hits/by_gene_KOG1458",
"../concat_alignment_hits/by_gene_KOG1463",
"../concat_alignment_hits/by_gene_KOG1466",
"../concat_alignment_hits/by_gene_KOG1468",
"../concat_alignment_hits/by_gene_KOG1487",
"../concat_alignment_hits/by_gene_KOG1491",
"../concat_alignment_hits/by_gene_KOG1494",
"../concat_alignment_hits/by_gene_KOG1498",
"../concat_alignment_hits/by_gene_KOG1506",
"../concat_alignment_hits/by_gene_KOG1523",
"../concat_alignment_hits/by_gene_KOG1526",
"../concat_alignment_hits/by_gene_KOG1531",
"../concat_alignment_hits/by_gene_KOG1532",
"../concat_alignment_hits/by_gene_KOG1533",
"../concat_alignment_hits/by_gene_KOG1534",
"../concat_alignment_hits/by_gene_KOG1535",
"../concat_alignment_hits/by_gene_KOG1539",
"../concat_alignment_hits/by_gene_KOG1540",
"../concat_alignment_hits/by_gene_KOG1541",
"../concat_alignment_hits/by_gene_KOG1549",
"../concat_alignment_hits/by_gene_KOG1555",
"../concat_alignment_hits/by_gene_KOG1556",
"../concat_alignment_hits/by_gene_KOG1562",
"../concat_alignment_hits/by_gene_KOG1566",
"../concat_alignment_hits/by_gene_KOG1567",
"../concat_alignment_hits/by_gene_KOG1568",
"../concat_alignment_hits/by_gene_KOG1596",
"../concat_alignment_hits/by_gene_KOG1597",
"../concat_alignment_hits/by_gene_KOG1626",
"../concat_alignment_hits/by_gene_KOG1636",
"../concat_alignment_hits/by_gene_KOG1637",
"../concat_alignment_hits/by_gene_KOG1641",
"../concat_alignment_hits/by_gene_KOG1643",
"../concat_alignment_hits/by_gene_KOG1644",
"../concat_alignment_hits/by_gene_KOG1646",
"../concat_alignment_hits/by_gene_KOG1647",
"../concat_alignment_hits/by_gene_KOG1654",
"../concat_alignment_hits/by_gene_KOG1662",
"../concat_alignment_hits/by_gene_KOG1664",
"../concat_alignment_hits/by_gene_KOG1668",
"../concat_alignment_hits/by_gene_KOG1678",
"../concat_alignment_hits/by_gene_KOG1688",
"../concat_alignment_hits/by_gene_KOG1691",
"../concat_alignment_hits/by_gene_KOG1692",
"../concat_alignment_hits/by_gene_KOG1712",
"../concat_alignment_hits/by_gene_KOG1722",
"../concat_alignment_hits/by_gene_KOG1723",
"../concat_alignment_hits/by_gene_KOG1727",
"../concat_alignment_hits/by_gene_KOG1728",
"../concat_alignment_hits/by_gene_KOG1733",
"../concat_alignment_hits/by_gene_KOG1742",
"../concat_alignment_hits/by_gene_KOG1746",
"../concat_alignment_hits/by_gene_KOG1750",
"../concat_alignment_hits/by_gene_KOG1753",
"../concat_alignment_hits/by_gene_KOG1754",
"../concat_alignment_hits/by_gene_KOG1755",
"../concat_alignment_hits/by_gene_KOG1758",
"../concat_alignment_hits/by_gene_KOG1760",
"../concat_alignment_hits/by_gene_KOG1762",
"../concat_alignment_hits/by_gene_KOG1769",
"../concat_alignment_hits/by_gene_KOG1770",
"../concat_alignment_hits/by_gene_KOG1772",
"../concat_alignment_hits/by_gene_KOG1774",
"../concat_alignment_hits/by_gene_KOG1775",
"../concat_alignment_hits/by_gene_KOG1779",
"../concat_alignment_hits/by_gene_KOG1780",
"../concat_alignment_hits/by_gene_KOG1781",
"../concat_alignment_hits/by_gene_KOG1782",
"../concat_alignment_hits/by_gene_KOG1784",
"../concat_alignment_hits/by_gene_KOG1795",
"../concat_alignment_hits/by_gene_KOG1800",
"../concat_alignment_hits/by_gene_KOG1816",
"../concat_alignment_hits/by_gene_KOG1872",
"../concat_alignment_hits/by_gene_KOG1885",
"../concat_alignment_hits/by_gene_KOG1889",
"../concat_alignment_hits/by_gene_KOG1915",
"../concat_alignment_hits/by_gene_KOG1936",
"../concat_alignment_hits/by_gene_KOG1942",
"../concat_alignment_hits/by_gene_KOG1979",
"../concat_alignment_hits/by_gene_KOG1980",
"../concat_alignment_hits/by_gene_KOG1986",
"../concat_alignment_hits/by_gene_KOG1992",
"../concat_alignment_hits/by_gene_KOG2004",
"../concat_alignment_hits/by_gene_KOG2014",
"../concat_alignment_hits/by_gene_KOG2017",
"../concat_alignment_hits/by_gene_KOG2035",
"../concat_alignment_hits/by_gene_KOG2036",
"../concat_alignment_hits/by_gene_KOG2044",
"../concat_alignment_hits/by_gene_KOG2047",
"../concat_alignment_hits/by_gene_KOG2067",
"../concat_alignment_hits/by_gene_KOG2104",
"../concat_alignment_hits/by_gene_KOG2189",
"../concat_alignment_hits/by_gene_KOG2270",
"../concat_alignment_hits/by_gene_KOG2276",
"../concat_alignment_hits/by_gene_KOG2292",
"../concat_alignment_hits/by_gene_KOG2303",
"../concat_alignment_hits/by_gene_KOG2309",
"../concat_alignment_hits/by_gene_KOG2311",
"../concat_alignment_hits/by_gene_KOG2321",
"../concat_alignment_hits/by_gene_KOG2387",
"../concat_alignment_hits/by_gene_KOG2415",
"../concat_alignment_hits/by_gene_KOG2446",
"../concat_alignment_hits/by_gene_KOG2451",
"../concat_alignment_hits/by_gene_KOG2467",
"../concat_alignment_hits/by_gene_KOG2472",
"../concat_alignment_hits/by_gene_KOG2481",
"../concat_alignment_hits/by_gene_KOG2509",
"../concat_alignment_hits/by_gene_KOG2519",
"../concat_alignment_hits/by_gene_KOG2529",
"../concat_alignment_hits/by_gene_KOG2531",
"../concat_alignment_hits/by_gene_KOG2535",
"../concat_alignment_hits/by_gene_KOG2537",
"../concat_alignment_hits/by_gene_KOG2555",
"../concat_alignment_hits/by_gene_KOG2572",
"../concat_alignment_hits/by_gene_KOG2574",
"../concat_alignment_hits/by_gene_KOG2575",
"../concat_alignment_hits/by_gene_KOG2606",
"../concat_alignment_hits/by_gene_KOG2613",
"../concat_alignment_hits/by_gene_KOG2617",
"../concat_alignment_hits/by_gene_KOG2623",
"../concat_alignment_hits/by_gene_KOG2636",
"../concat_alignment_hits/by_gene_KOG2638",
"../concat_alignment_hits/by_gene_KOG2653",
"../concat_alignment_hits/by_gene_KOG2670",
"../concat_alignment_hits/by_gene_KOG2680",
"../concat_alignment_hits/by_gene_KOG2700",
"../concat_alignment_hits/by_gene_KOG2703",
"../concat_alignment_hits/by_gene_KOG2707",
"../concat_alignment_hits/by_gene_KOG2711",
"../concat_alignment_hits/by_gene_KOG2719",
"../concat_alignment_hits/by_gene_KOG2726",
"../concat_alignment_hits/by_gene_KOG2728",
"../concat_alignment_hits/by_gene_KOG2732",
"../concat_alignment_hits/by_gene_KOG2738",
"../concat_alignment_hits/by_gene_KOG2749",
"../concat_alignment_hits/by_gene_KOG2754",
"../concat_alignment_hits/by_gene_KOG2757",
"../concat_alignment_hits/by_gene_KOG2767",
"../concat_alignment_hits/by_gene_KOG2770",
"../concat_alignment_hits/by_gene_KOG2772",
"../concat_alignment_hits/by_gene_KOG2775",
"../concat_alignment_hits/by_gene_KOG2781",
"../concat_alignment_hits/by_gene_KOG2783",
"../concat_alignment_hits/by_gene_KOG2784",
"../concat_alignment_hits/by_gene_KOG2785",
"../concat_alignment_hits/by_gene_KOG2792",
"../concat_alignment_hits/by_gene_KOG2803",
"../concat_alignment_hits/by_gene_KOG2807",
"../concat_alignment_hits/by_gene_KOG2825",
"../concat_alignment_hits/by_gene_KOG2833",
"../concat_alignment_hits/by_gene_KOG2851",
"../concat_alignment_hits/by_gene_KOG2854",
"../concat_alignment_hits/by_gene_KOG2855",
"../concat_alignment_hits/by_gene_KOG2874",
"../concat_alignment_hits/by_gene_KOG2877",
"../concat_alignment_hits/by_gene_KOG2906",
"../concat_alignment_hits/by_gene_KOG2908",
"../concat_alignment_hits/by_gene_KOG2909",
"../concat_alignment_hits/by_gene_KOG2916",
"../concat_alignment_hits/by_gene_KOG2930",
"../concat_alignment_hits/by_gene_KOG2948",
"../concat_alignment_hits/by_gene_KOG2952",
"../concat_alignment_hits/by_gene_KOG2957",
"../concat_alignment_hits/by_gene_KOG2967",
"../concat_alignment_hits/by_gene_KOG2971",
"../concat_alignment_hits/by_gene_KOG2981",
"../concat_alignment_hits/by_gene_KOG2988",
"../concat_alignment_hits/by_gene_KOG3013",
"../concat_alignment_hits/by_gene_KOG3022",
"../concat_alignment_hits/by_gene_KOG3031",
"../concat_alignment_hits/by_gene_KOG3048",
"../concat_alignment_hits/by_gene_KOG3049",
"../concat_alignment_hits/by_gene_KOG3052",
"../concat_alignment_hits/by_gene_KOG3064",
"../concat_alignment_hits/by_gene_KOG3079",
"../concat_alignment_hits/by_gene_KOG3090",
"../concat_alignment_hits/by_gene_KOG3106",
"../concat_alignment_hits/by_gene_KOG3147",
"../concat_alignment_hits/by_gene_KOG3149",
"../concat_alignment_hits/by_gene_KOG3157",
"../concat_alignment_hits/by_gene_KOG3163",
"../concat_alignment_hits/by_gene_KOG3164",
"../concat_alignment_hits/by_gene_KOG3167",
"../concat_alignment_hits/by_gene_KOG3174",
"../concat_alignment_hits/by_gene_KOG3180",
"../concat_alignment_hits/by_gene_KOG3185",
"../concat_alignment_hits/by_gene_KOG3188",
"../concat_alignment_hits/by_gene_KOG3189",
"../concat_alignment_hits/by_gene_KOG3204",
"../concat_alignment_hits/by_gene_KOG3205",
"../concat_alignment_hits/by_gene_KOG3218",
"../concat_alignment_hits/by_gene_KOG3222",
"../concat_alignment_hits/by_gene_KOG3229",
"../concat_alignment_hits/by_gene_KOG3232",
"../concat_alignment_hits/by_gene_KOG3237",
"../concat_alignment_hits/by_gene_KOG3239",
"../concat_alignment_hits/by_gene_KOG3271",
"../concat_alignment_hits/by_gene_KOG3273",
"../concat_alignment_hits/by_gene_KOG3275",
"../concat_alignment_hits/by_gene_KOG3283",
"../concat_alignment_hits/by_gene_KOG3284",
"../concat_alignment_hits/by_gene_KOG3285",
"../concat_alignment_hits/by_gene_KOG3291",
"../concat_alignment_hits/by_gene_KOG3295",
"../concat_alignment_hits/by_gene_KOG3297",
"../concat_alignment_hits/by_gene_KOG3301",
"../concat_alignment_hits/by_gene_KOG3311",
"../concat_alignment_hits/by_gene_KOG3313",
"../concat_alignment_hits/by_gene_KOG3318",
"../concat_alignment_hits/by_gene_KOG3320",
"../concat_alignment_hits/by_gene_KOG3330",
"../concat_alignment_hits/by_gene_KOG3343",
"../concat_alignment_hits/by_gene_KOG3349",
"../concat_alignment_hits/by_gene_KOG3361",
"../concat_alignment_hits/by_gene_KOG3372",
"../concat_alignment_hits/by_gene_KOG3387",
"../concat_alignment_hits/by_gene_KOG3400",
"../concat_alignment_hits/by_gene_KOG3404",
"../concat_alignment_hits/by_gene_KOG3405",
"../concat_alignment_hits/by_gene_KOG3406",
"../concat_alignment_hits/by_gene_KOG3411",
"../concat_alignment_hits/by_gene_KOG3418",
"../concat_alignment_hits/by_gene_KOG3428",
"../concat_alignment_hits/by_gene_KOG3430",
"../concat_alignment_hits/by_gene_KOG3432",
"../concat_alignment_hits/by_gene_KOG3436",
"../concat_alignment_hits/by_gene_KOG3442",
"../concat_alignment_hits/by_gene_KOG3448",
"../concat_alignment_hits/by_gene_KOG3449",
"../concat_alignment_hits/by_gene_KOG3453",
"../concat_alignment_hits/by_gene_KOG3457",
"../concat_alignment_hits/by_gene_KOG3459",
"../concat_alignment_hits/by_gene_KOG3463",
"../concat_alignment_hits/by_gene_KOG3464",
"../concat_alignment_hits/by_gene_KOG3475",
"../concat_alignment_hits/by_gene_KOG3479",
"../concat_alignment_hits/by_gene_KOG3480",
"../concat_alignment_hits/by_gene_KOG3482",
"../concat_alignment_hits/by_gene_KOG3489",
"../concat_alignment_hits/by_gene_KOG3493",
"../concat_alignment_hits/by_gene_KOG3497",
"../concat_alignment_hits/by_gene_KOG3498",
"../concat_alignment_hits/by_gene_KOG3499",
"../concat_alignment_hits/by_gene_KOG3502",
"../concat_alignment_hits/by_gene_KOG3503",
"../concat_alignment_hits/by_gene_KOG3506",
"../concat_alignment_hits/by_gene_KOG3855",
"../concat_alignment_hits/by_gene_KOG3954",
"../concat_alignment_hits/by_gene_KOG3974",
"../concat_alignment_hits/by_gene_KOG4392",
"../concat_alignment_hits/by_gene_KOG4655");

@gene_list_short = (
"../concat_alignment_hits/by_gene_KOG0002",
"../concat_alignment_hits/by_gene_KOG0003",
"../concat_alignment_hits/by_gene_KOG0018",
"../concat_alignment_hits/by_gene_KOG0019",
"../concat_alignment_hits/by_gene_KOG0025");

@gene_list_single = (
"../concat_alignment_hits/by_gene_KOG0025");

#work out which gene list to use.
@gene_list;
if($ARGV[2] eq "long"){
	@gene_list = @gene_list_long;
}else{
	if($ARGV[2] eq "short"){
		@gene_list = @gene_list_short;
	}else{
		@gene_list = @gene_list_single;
	}
}
$number_of_loci = scalar(@gene_list);
warn "Number of genes in phylogenetic analysis: [$number_of_loci]\n";

warn "\nblast";
print "blast\n";
#BLAST (sequential)
#$com="time blastp -query ../MG-RAST/short.input.faa -db concatenated_CEGMA_aa.fa -outfmt \"6 qseqid sseqid evalue bitscore length\" -max_target_seqs 1 -evalue 1e-10 -out smallerHits ";
#BLAST (*multi-threaded*)
$com="time -p blastp -query ../MG-RAST/short.input.faa -db concatenated_CEGMA_aa.fa -outfmt \"6 qseqid sseqid evalue bitscore length\" -max_target_seqs 1 -evalue 1e-10 -out smallerHits -num_threads $threads";
system($com);

#concatenate
warn "\nconcatenate";
$com="perl concat_aligns_hits.pl smallerHits ";
system($com);

#iterate over gene list. Initially only short list
$counter = 0;
$time_start = time();
foreach $gene(@gene_list){
	#report counter
	warn "Analysing locus [$counter]\n";
	print "Analysing locus [$counter]\n";

	#get just the KOG ID for each gene without the leading filepath
	$gene_short_ID = substr($gene,-7,7);
	
	#muscle
	warn "\nmuscle_analysis $gene\n";
	$com="time -p muscle -in $gene -phyiout ../phylogenetics/$gene_short_ID.phyi -quiet >/dev/null 2>/dev/null";
	system($com);
	
	#RAxML
	chdir('../phylogenetics');
	warn "\nRAxML_analysis $gene\n";
	#RAxML - PTHREADS option
	$com="time -p $bin_raxml -m PROTCATDAYHOFF -s $gene_short_ID.phyi -n t$gene_short_ID  -T $threads >/dev/null 2>/dev/null";
	#RAXML - sequential option
	#$com="time $bin_raxml -m PROTCATDAYHOFF -s $gene_short_ID.phyi -n t$gene_short_ID >/dev/null 2>/dev/null";
	system($com);
	chdir('../BLAST-dbs');
	
	#increment counter
	$counter++;
}
$time_end = time();
#calculate elapsed time for phylogenetics
warn "\nphylotime (all loci) ".($time_end-$time_start)."s (rounded)\n";

warn "\ndone.\n\n";